import "./globals.css";
import { UserContextProvider } from "./Context/UserContext";
import { NoteContextProvider } from "./Context/NoteContext";
import { AlertContextProvider } from "./Context/AlertContext";
import { JetBrains_Mono } from "next/font/google";
const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"]
  , weight: ["100", "200"]
  , style: ["normal", "italic"]
})

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${jetBrainsMono.className} antialiased`}
      >
        <AlertContextProvider>
          <UserContextProvider>
            <NoteContextProvider>
              
              {children}
            </NoteContextProvider>
          </UserContextProvider>
        </AlertContextProvider>
      </body>
    </html>
  );
}
